# -*- coding: utf-8 -*-
"""Practical no 6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gq6TzG6O5NKks3SByd3wpBrXsBEiltH8
"""

# Take string input from user
text = input("Enter a string: ")

# Initialize counters
vowels = 0
consonants = 0
spaces = 0
lowercase = 0

# Define vowels
vowel_letters = "aeiouAEIOU"

# Loop through each character
for ch in text:
    if ch in vowel_letters:
        vowels += 1
    elif ch.isalpha():
        consonants += 1

    if ch == " ":
        spaces += 1

    if ch.islower():
        lowercase += 1

# Display results
print("Number of Vowels:", vowels)
print("Number of Consonants:", consonants)
print("Number of Spaces:", spaces)
print("Number of Lowercase Letters:", lowercase)

# Function definition
def capitalize_sentence(line):
    result = line.upper()
    print(result)

# Take input from user
text = input("Enter a sentence: ")

# Function call
capitalize_sentence(text)