# -*- coding: utf-8 -*-
"""Copy of Practical no 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s0Rw7CHfGsPSFpCw9payqRNDywd1IYQN
"""

# Take input from user
nums = tuple(map(int, input("Enter integers separated by space: ").split()))

# a) Total number of items
print("Total number of items:", len(nums))

# b) Last item
print("Last item in tuple:", nums[-1])

# c) Tuple in reverse order
print("Tuple in reverse order:", nums[::-1])

# d) Check if 5 is present
if 5 in nums:
    print("Yes")
else:
    print("No")

# e) Remove first and last items, sort remaining items
if len(nums) > 2:
    new_tuple = nums[1:-1]          # remove first and last
    sorted_tuple = tuple(sorted(new_tuple))
    print("Sorted tuple after removing first and last items:", sorted_tuple)
else:
    print("Not enough elements to remove first and last items.")

# Take input from user
data = input("Enter prices of sold items separated by space: ")

# Convert input into list first
price_list = []
for item in data.split():
    price_list.append(float(item))

# Convert list into tuple
prices = tuple(price_list)

# a) Total number of items sold
print("Total number of items sold:", len(prices))

# b) Cheapest item price
print("Price of cheapest item:", min(prices))

# c) Costliest item price
max_price = max(prices)
print("Price of costliest item:", max_price)

# d) Prices in ascending order
sorted_prices = tuple(sorted(prices))
print("Prices in ascending order:", sorted_prices)

# e) Number of costliest items sold
count_max = prices.count(max_price)
print("Number of costliest items sold:", count_max)
