# -*- coding: utf-8 -*-
"""Practical no 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u6go1vW_K2deNB-F1H0vUQblEZlqXTAE
"""

# Functions
def add(a, b):
    return a + b

def sub(a, b):
    return a - b

def mul(a, b):
    return a * b

def div(a, b):
    return a / b

def mod(a, b):
    return a % b


# Menu
print("---- CALC MENU ----")
print("1. Addition")
print("2. Subtraction")
print("3. Multiplication")
print("4. Division")
print("5. Modulus")

choice = int(input("Enter choice: "))

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

if choice == 1:
    print("Result =", add(a, b))

elif choice == 2:
    print("Result =", sub(a, b))

elif choice == 3:
    print("Result =", mul(a, b))

elif choice == 4:
    print("Result =", div(a, b))

elif choice == 5:
    print("Result =", mod(a, b))

else:
    print("Invalid choice")

balance = 1000   # starting balance

# Display balance
def display():
    print("Current Balance =", balance)

# Deposit money
def deposit():
    global balance
    amt = int(input("Enter amount to deposit: "))
    balance = balance + amt
    print("Money Deposited")

# Withdraw money
def withdraw():
    global balance
    amt = int(input("Enter amount to withdraw: "))

    if amt <= balance:
        balance = balance - amt
        print("Money Withdrawn")
    else:
        print("Not enough balance")

# Menu
while True:
    print("\n--- BANK MENU ---")
    print("1. Display Balance")
    print("2. Deposit")
    print("3. Withdraw")
    print("4. Exit")

    choice = int(input("Enter choice: "))

    if choice == 1:
        display()
    elif choice == 2:
        deposit()
    elif choice == 3:
        withdraw()
    elif choice == 4:
        print("Thank You")
        break
    else:
        print("Wrong choice")