# -*- coding: utf-8 -*-
"""python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vXV7TbSf69TCMo9mlcGBIpCqp35Sd3UI
"""

for i in range(1, 6):
  for j in range(1, i + 1):
    print(j, end="")
  print()

for i in range(1, 6):
  for j in range(i):
    print(i, end="")
  print()

for i in range(1, 6):
  for j in range(i, 0, -1):
    print(j, end="")
  print()

for i in range(1,6):
  for j in range(1, i + 1):
    print(j % 2, end="")
  print()

num = 2
for i in range(1, 5):
  for j in range(i):
    print(num, end=" ")
    num += 2
  print()

for i in range(1, 6):
  for j in range(i):
    print("*", end="")
  print()

for i in range(1, 6):
  for j in range(i):
    print(chr(65 + j), end="")
  print()

for i in range(1, 5):
  for j in range(i):
    print("*",end=" ")
  print()

word = "python"
for i in range(len(word)):
  print(word[i] * (i + 1))

n = int(input())
for i in range(1, n + 1):
  print(i, end="")

for i in range(6, 0, -1):
    print(" " * (6 - i) + "* " * i)

rows = 5

for i in range(rows):
    # spaces
    for s in range(rows - i - 1):
        print("  ", end="")

    # stars
    for j in range(2 * i + 1):
        print("* ", end="")

    print()

n = 5

# upper part
for i in range(1, n + 1):
    for j in range(i):
        print("*", end=" ")
    print()

# lower part
for i in range(n - 1, 0, -1):
    for j in range(i):
        print("*", end=" ")
    print()

# Input using while loop (validation)
while True:
    start = int(input("Enter first number: "))
    end = int(input("Enter second number: "))

    if start < end:
        break
    else:
        print("First number must be smaller than second. Try again!")

print("Prime numbers between", start, "and", end, "are:")

# Prime checking using for loop
for num in range(start, end + 1):
    if num > 1:
        prime = True
        for i in range(2, num):
            if num % i == 0:
                prime = False
                break

        if prime:
            print(num)

